### ISSUE TITLE
Add licence to project

### ISSUE THREAD

**Issue by cweiers** [philsturgeon/json-schema-to-openapi-schema#23]
As of right now, I am unsure if I am allowed to use this (and under which circumstances I might be allowed to). Please consider adding a licence (whichever you feel is appropriate), so that users interested in this project know if they can use this or not.

**Comment by philsturgeon** [comment]
It's MIT https://github.com/wework/json-schema-to-openapi-schema/blob/master/package.json#L12

**Comment by cweiers** [comment]
Well, that's solved then :) thank you, I kinda missed it there.
