### ISSUE TITLE
Document that OpenAPI 2.0 is supported

### ISSUE THREAD

**Issue by ehmicky** [philsturgeon/json-schema-to-openapi-schema#7]
This package actually also support OpenAPI 2.0.

Most of the OpenAPI ecosystem is (unfortunately) still stuck on 2.0 version, so documenting the fact this library supports it might be a good idea?

The differences are as follow:
  - OpenAPI 2.0-only:
     - `type` `file`
  - OpenAPI 3.0-only:
     - `oneOf`, `anyOf` and `not` (from JSON schema v4)
     - `writeOnly` (from JSON schema v7)
     - `deprecated`
     - `nullable`
  - OpenAPI 2.0/3.0 differences:
     - `discriminator` is a `string` (property name) in 2.0 and is `{ propertyName: string, mapping object }` in 3.0

**Comment by philsturgeon** [comment]
Sorry @ehmicky, most of my open-source-at-work time is going into making various tools support OpenAPI v3.0. My day-job is OpenAPI v3.0 only, so putting any sort of time into supporting v2.0 is cutting into the roadmap, or cutting into bike time. 

If you'd like to send some sort of pull request then I'd really appreciate that. 😬
